# Generated by Django 5.0.4 on 2024-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_cover_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
