# Generated by Django 5.0.4 on 2024-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_cover_alter_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
