# Generated by Django 5.0.4 on 2024-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hwtb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
