# Generated by Django 5.0.4 on 2024-05-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_hwtb_game_hltb_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
